name: build DicomGrep

on: 
  push:
    branches-ignore:
      - 'archive'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches-ignore:
      - 'archive'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        configuration: 
          - Debug
          #- Release
        dotnet-version:
          - '6.0.x'
    # for create new releases
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build DicomGrep/DicomGrep.csproj --no-restore --configuration ${{ matrix.configuration }} --output bin/net${{ matrix.dotnet-version }}/${{ matrix.configuration }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Upload articraft
      uses: actions/upload-artifact@v4
      with:
        name: DicomGrep-${{ matrix.configuration }}
        path: |
          bin/net${{ matrix.dotnet-version }}/${{ matrix.configuration }}
          !bin/**/DICOM Dictionary.xml
          !bin/**/Private Dictionary.xml